version: "3.8"
services:
  mysql:
    image: mysql
    volumes:
      -  ./mysql:/var/lib/mysql
    ports: 
     - 3306:3306   
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
        test: ["CMD-SHELL", "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SELECT 1'"]
        interval: 10s
        timeout: 5s
        retries: 20
  shortenit:
    image: shortenit
    restart: always
    build: .
    ports:
      - 9999:9999
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
